id: 9e82085770424a8db9183ee92e9e27dd
initial_creation_type: ocr
source_metadata:
  volumes:
    c82d3cd4efe744ea847d47fc2e5e9235:
      base_file: v106.txt
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1891
      volume_number: 107
