id: D793A898F
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2021-11-12T08:58:39+00:00'
last_modified: '2022-05-30T04:55:09.407912+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/a7eec5e12ddce18d0ed1dbb732a42cf48f94dd09/openpecha/formatters/hfml.py
source_metadata:
  base:
    a054:
      image_group_id: I1PD95952
      title: དེ་ཁོ་ན་ཉིད་བསྡུས་པའི་ཚིག་ལེའུར་བྱས་པ།
      total_pages: 1891
      order: 107
      base_file: a054.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
